export const backgrounds = [
  'Grassy Plains',
  'Dance Hall',
  'Clean Sky',
  'Cerulean',
  'Morning Sun',
  'Hot Sand',
  'World at Dusk',
  'Cozy Bedroom',
];

export const smokesticks = ['Cigar', 'Cigarette', "Farmer's Gum", 'Corn Cob Pipe', 'Wood Pipe', 'Jamaican Hay'];

export const banditMasks = [
  'Red Bandana',
  'Green Polka Rag',
  'Gray Polka Rag',
  'Blue Polka Rag',
  'Red Polka Rag',
  'Gray Bandana',
];

export const kicks = ['Cowboy Boots', 'Loafers', 'Dance Shoes', 'Oxford Shoes', 'Brogues', 'Mining Boots'];

export const shades = ['Shine Shades'];

export const trousers = [
  'Breeches',
  'Leather Pants',
  'Selvedge Denim Pants',
  'Khaki Chino',
  'Velvet Pants',
  'Jong Johns',
  'Stuntman Pants',
  'Sunday Pants',
  'Faded Jeans',
];

export const disguises = [
  'Vader Mask',
  'MF DOOM Mask',
  'Zombie Mask',
  'Clown Mask',
  'Skelly Mask',
  'Spider Mask',
  'Iron Mask',
  'Bat Mask',
  'OG Bat Mask',
  'Hannibal Mask',
  'Scream Mask',
  'Zorro Mask',
  'V Mask',
  'Nacho Mask',
  'R0b0 Mask',
];

export const headgears = [
  'Blue Do-Rag',
  'Red Trucker Hat',
  'Blue Trucker Hat',
  '‘TIS BUT A SCRATCH 1',
  '‘TIS BUT A SCRATCH 2',
  '‘TIS BUT A SCRATCH 3',
  'Brown Fedora',
  'Black Fedora',
  'Metal Helmet',
  'Miner Gear',
  'Poker Hat',
  'Balaclava',
  'Ski Mask',
  'Red Bandana',
  'Straw Sombrero',
  'Black Sombrero',
  'Red Feather Pork Pie',
  'Purple Feather Pork Pie',
  'Bandit Fedora',
  'The Dandy Red',
  'The Dandy Blue',
  'The Dundee',
  'The Gray Buckaroo',
  'The Gold Buckaroo',
  'The Peaky',
  'The Heisneberg',
  'The Black Bowler',
  'The Rust Bowler',
  'The Blue Bowler',
  'The Johnny Ringo',
  'Ten Gallon',
  'Ten Gallon Arrow',
  'Red Backwards Cap',
  'Grey Backwards Cap',
  'Green Backwards Cap',
  'Blue Backwards Cap',
  'Red Fitted Cap',
  'Grey Fitted Cap',
  'Green FItted Cap',
  'Blue Fitted Cap',
  'Red Slouched Beanie',
  'Green Slouched Beanie',
  'Khaki Military Beanie',
  'Red Knit Beanie',
];

export const habiliments = [
  'Rolled-Sleve Shirt',
  'Dandy Shirt',
  'Daily Shirt',
  'Clean Buckskin Shirt',
  'Plaid Shirt',
  'Brown Leather Vest',
  'Black Leather Vest',
  'Sunday Pants',
  'Army Jacket',
  'Biker Jacket',
  'Navy Shirt',
  'Inmate Shirt',
  "Doctor's Lab Coat",
  "Sheriff's Garb",
  'Sunday Best',
  'Office Suite',
  'Buckskin Shirt',
  'Dress Shirt',
  "Farmer's Shirt",
];

export const whiskersAndChinCurtains = [
  'The Horseshoe Red',
  'The Horseshoe Blonde',
  'The Horseshoe Black',
  'The Gunslinger Blonde',
  'The Gunslinger Black',
  'The Gunslinger Brown',
  'The Walrus Blonde',
  'The Walrus Brown',
  'The Walrus Black',
  'The Gentleman Red',
  'The Gentleman Blonde',
  'The Gentleman Brown',
  'The Gentleman Black',
  'The Villain',
  'The Pancho Villa',
  'Salt and Peper Beard',
  'Blonde Beard',
  'Red Beard',
  'Black Beard',
];
